### ISSUE TITLE
Vue 2 support

### ISSUE THREAD

**Issue by ajerez** [jpkleemans/vite-svg-loader#10]
Any plans to support vue 2?

I have this error in a vite project with vue 2:

**Uncaught SyntaxError: The requested module '/node_modules/.vite/vue.js' does not provide an export named 'Fragment**

Thanks

**Comment by jpkleemans** [comment]
Hi, Vite doesn't support Vue 2 at the moment. See https://github.com/vitejs/vite/issues/305

**Comment by rightaway** [comment]
@jpkleemans With vite-plugin-vue2 vite can be used with Vue 2. Would you consider adding support for Vue 2? Will be a while before Vue 3 becomes used by everyone.

**Comment by rogatty** [comment]
See https://github.com/pakholeung37/vite-plugin-vue2-svg for an alternative.

**Comment by jaw52** [comment]
Both vue2 and vue3 are supported https://www.npmjs.com/package/unplugin-svg-vue-component
