### ISSUE TITLE
Does the loader support Vue 2.7?

### ISSUE THREAD

**Issue by kassuro** [jpkleemans/vite-svg-loader#109]
Hello, 

I have a question regarding the support of Vue 2.7 as the readme doesn't mention it.

We tried it today and we couldn't get it to work.

Is Vue 2.7 supported and / or should it work?

**Comment by adeacetis** [comment]
+1

**Comment by Ajay537** [comment]
+1

**Comment by adeacetis** [comment]
For those searching a solution we implemented `https://www.npmjs.com/package/vite-plugin-vue2-svg` and it seems to be working just fine for us in `development` stage, we haven't pushed to `production` yet.

**Comment by jpkleemans** [comment]
This plugin only supports Vue 3
