### ISSUE TITLE
Cannot load svg with ?url

### ISSUE THREAD

**Issue by gawlk** [jpkleemans/vite-svg-loader#11]
Hi,

Great job it works great but sometimes I need to load the SVGs from their URL and this library disables the possibility, could you allow such imports ?

Thank you

**Comment by jpkleemans** [comment]
Hi, loading external URLs is not supported.
Could you share some code how you'd like to import the SVGs from their URL?

**Comment by gawlk** [comment]
Sure, like so

`import svgURL from '../assets/icon.svg'`
