### ISSUE TITLE
Publish newest version 4.1.0 to npm registry

### ISSUE THREAD

**Issue by typeonerogue** [jpkleemans/vite-svg-loader#110]
I would love to take advantage of the work done in this PR https://github.com/jpkleemans/vite-svg-loader/pull/92

The current version on npm is 4.0.0, could you please push the new 4.1.0 release out to npm registry?

Thanks!

**Comment by DirectorRen-TV** [comment]
@jpkleemans 
@gkatsanos

**Comment by gkatsanos** [comment]
I unfortunately don't have npm publish privileges. I'll try to contact @jpkleemans .

**Comment by DirectorRen-TV** [comment]
@jpkleemans please publish new version to npm

**Comment by vincerubinetti** [comment]
I'm installing with `yarn add jpkleemans/vite-svg-loader#v4.1.0` for now (yuck). Please publish!
