### ISSUE TITLE
Preserve viewbox

### ISSUE THREAD

**Issue by Aybee5** [jpkleemans/vite-svg-loader#123]
#120 mentions a way to preserve 'viewbox', I've spent some time experimenting with how to safeguard that before finally seeing the PR. It would be helpful if the PR got merged 🙏🏾

**Comment by jpkleemans** [comment]
Thanks for mentioning it! I'll merge it soon, please follow the progress at the [PR](https://github.com/jpkleemans/vite-svg-loader/pull/120)

**Comment by MickL** [comment]
Has this been published @jpkleemans ? I am on `5.1.0` and viewbox is not preserved.

**Comment by C-gotoh** [comment]
@MickL The mentioned PR just adds documentation how to change the configuration to preserve the viewBox, it does not need to be merged for you to apply it. Unfortunately the default setting used in the svgo library won't change in the near future.

**Comment by jgaehring** [comment]
Copy'n'pasting the additions to the README for lazy ppl like me who feel overwhelmed by clicking through to another link. 😉 

> By default, SVGO does not preserve the `viewBox` attribute for optimization reasons. This can cause issues when you need to resize your SVG with CSS. You can pass options to `svgLoader()` to disable the removal of the `viewBox` attribute.
> 
> ```js
> svgLoader({
>   svgoConfig: {
>     multipass: true,
>     plugins: [
>       {
>         name: 'preset-default',
>         params: {
>           overrides: {
>             // @see https://github.com/svg/svgo/issues/1128
>             removeViewBox: false,
>           },
>         },
>       },
>     ],
>   },
> }),
> ```

Works great for me! Thx y'all!! 🙏🏻
