### ISSUE TITLE
Seems not working after update Vite to 5.0

### ISSUE THREAD

**Issue by sergiocarracedo** [jpkleemans/vite-svg-loader#124]
After update the project to vite 5.0.0 got the following error ` [ERROR] No loader is configured for ".svg" files:`

Reproduction steps: 
 - Upgrade the project to vite 5.0.0
 - start the project

**Comment by sergiocarracedo** [comment]
I added this PR to solve it https://github.com/jpkleemans/vite-svg-loader/pull/125

**Comment by jpkleemans** [comment]
Fixed in [release 5.0.0](https://github.com/jpkleemans/vite-svg-loader/releases/tag/5.0.0)
