### ISSUE TITLE
vite5.0 bug

### ISSUE THREAD

**Issue by ZombieBrand** [jpkleemans/vite-svg-loader#128]
<img width="1502" alt="image" src="https://github.com/jpkleemans/vite-svg-loader/assets/27719748/f8d0b0a6-23ec-4883-a6d8-be358c5b509a">

**Comment by jpkleemans** [comment]
Vite 5 deprecated the CJS Node API, see https://vitejs.dev/guide/migration#deprecate-cjs-node-api
You can fix it by setting "type": "module" in your package.json file

**Comment by jpkleemans** [comment]
Actually I reverted this in release [5.1.0](https://github.com/jpkleemans/vite-svg-loader/releases/tag/5.1.0) so now the error should be gone without the need to adjust something.
