### ISSUE TITLE
No loader is configured for ".svg" for dynamic import

### ISSUE THREAD

**Issue by grindpride** [jpkleemans/vite-svg-loader#132]
I have this code to dynamically import icon component
```ts
const currentIcon = computed(() => {
  const { name } = props

  return defineAsyncComponent(() => import(`../../assets/icons/sized/${name}.svg`))
})

  ```
  
  Error `No loader is configured for ".svg"` occurred after start dev build
  
  Works well, when i use common import
  
  ```ts
  import DefaultIcon from '../../assets/icons/sized/error.svg?component'

  const currentIcon = computed(() => DefaultIcon)
```
  
  vite 5.0.0
  vite-svg-loader 5.1.0

**Comment by grindpride** [comment]
Looks like packages was incorrectly cached. No longer reproduces.

**Comment by beefchimi** [comment]
I am hitting this issue whenever I run the `vite` command. No amount of re-installing has managed to resolve this... @grindpride any chance you changed anything else to resolve your issue?

I am on `vite 5.0.2` and `vite-svg-loader 5.1.0`.

**Re-installing packages:**

`rm -rf node_modules && rm -rf package-lock.json && npm cache clean --force && npm install`

Also, I actually get the exact same error when attempting to run `vite` in this project's `/examples` directory. @jpkleemans any advice?
