### ISSUE TITLE
style tag are gone

### ISSUE THREAD

**Issue by yoyoys** [jpkleemans/vite-svg-loader#14]
If svg file contains `style` tag.
There will only render `defs` tag without `style` tag.

This plugin should have more options such as `prefixIds`.

**Comment by jpkleemans** [comment]
Hi, all styles should be added inline. You can use [SVGO](https://jakearchibald.github.io/svgomg/) to convert your SVG's

**Comment by jpkleemans** [comment]
There are options to preserve the styling. See https://github.com/jpkleemans/vite-svg-loader/issues/56#issuecomment-1160290025
