### ISSUE TITLE
Support ?raw parameter to get the string instead of a component

### ISSUE THREAD

**Issue by gawlk** [jpkleemans/vite-svg-loader#20]
Hi !

99% of the time we want a component but it happens that we need to have the raw value of an svg.
Currently in those cases it's not possible to have the raw value of the file as it is without the plugin.
It'd be awesome if this parameter was added.

**Comment by jpkleemans** [comment]
This is now supported, from version [2.2.0](https://github.com/jpkleemans/vite-svg-loader/releases/tag/2.2.0)
