### ISSUE TITLE
dynamically import not working when build

### ISSUE THREAD

**Issue by zinken7** [jpkleemans/vite-svg-loader#24]
@jpkleemans Hi, I used this but failed when build for production.
It's working in dev mode
```
<script lang="ts">
  import { computed, defineComponent, defineAsyncComponent } from 'vue'
  export default defineComponent({
    props: {
      name: {
        type: String,
        default: undefined,
      },
    },
    setup(props) {
      const currentIcon = computed(() => defineAsyncComponent(() => import(`../../icons/${props.name}.svg?component`))).value
      return {
        currentIcon
      }
    }
  })
</script>
```

**Comment by jpkleemans** [comment]
Hi, thanks for reporting. Could you share an example project so I can reproduce the problem, and investigate how to resolve it.

**Comment by zinken7** [comment]
I made an example here:
https://github.com/zinken7/vite_svg_inline
It only working on dev mode. It's not working  when build.
Live example:
https://codesandbox.io/s/epic-williamson-sfmb5

**Comment by eduredon** [comment]
The `enforce` property seems to be the cause of the problem. If you remove it, you can see how the build works in production.
<img width="126" alt="Captura de pantalla 2022-01-12 a las 13 50 50" src="https://user-images.githubusercontent.com/8898272/149143882-f4417960-6b6b-4f96-9615-0afa5e7c6e90.png">

**Comment by jpkleemans** [comment]
@zinken7 does it work when omitting the `?component` param?

**Comment by jpkleemans** [comment]
@silencerspirit thanks for posting your solution!

**Comment by cdwmhcc** [comment]
> import { h } from 'vue';
> 
> const CommonIcon = (props, context) => {
>  const svg = require(`../../assets/svg/${props.name}.svg`).default;
>  return h('span', {...context.attrs, class: 'common-icon', }, [
>     h(svg, { class: 'h-[inherit] w-[inherit]' }, [h(svg)]),
>   ]);
> }
> 
> CommonIcon.props = {
>   name: {
>     type: String,
>     required: true,
>   },
>   width: {
>     type: String,
>     default: '',
>   },
>   height: {
>     type: String,
>     default: '',
>   },
>   size: {
>     type: String,
>     default: '',
>   },
> };
> 
> export default CommonIcon;

require is not defined

**Comment by cdwmhcc** [comment]
> @cdwmhcc you need install plugin `vite-require`;
> 
> In `vite.config.ts`:
> 
> ```
> import svgLoader from 'vite-svg-loader';
> import { viteRequire } from 'vite-require';
> 
> export default {
>   ...,
>   plugins: [svgLoader(), viteRequire()]
> };
> ```
> 
> and if you use `vitest` as test platform, in `vitest.config.ts`:
> 
> ```
> import { viteRequire } from 'vite-require';
> import svgLoader from 'vite-svg-loader';
> import vue from '@vitejs/plugin-vue';
> 
> export default defineConfig({
>   ...,
>   plugins: [vue(), viteRequire(), svgLoader()],
> });
> ```

Not working in nuxt.js 3

**Comment by silencerspirit** [comment]
> > @cdwmhcc you need install plugin `vite-require`;
> > In `vite.config.ts`:
> > ```
> > import svgLoader from 'vite-svg-loader';
> > import { viteRequire } from 'vite-require';
> > 
> > export default {
> >   ...,
> >   plugins: [svgLoader(), viteRequire()]
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and if you use `vitest` as test platform, in `vitest.config.ts`:
> > ```
> > import { viteRequire } from 'vite-require';
> > import svgLoader from 'vite-svg-loader';
> > import vue from '@vitejs/plugin-vue';
> > 
> > export default defineConfig({
> >   ...,
> >   plugins: [vue(), viteRequire(), svgLoader()],
> > });
> > ```
> 
> Not working in nuxt.js 3

U welcome https://stackblitz.com/edit/github-1ck5ek?file=app.vue :)

**Comment by cdwmhcc** [comment]
> 

I can't get it to work locally in windows11, it's weird.

**Comment by cdwmhcc** [comment]
@silencerspirit Thank you for your reply. It will load all icons. I need to load on demand.
