### ISSUE TITLE
vite svg loader with typescript gives error when running jest test

### ISSUE THREAD

**Issue by ahyagoub40** [jpkleemans/vite-svg-loader#27]
```
    Configuration error:
    
    Could not locate module @assets/images/icon-calendar.svg?component mapped as:
    /Users/ahmedyagoub/plankk/phoenix/src/assets/$1.
    
    Please check your configuration for these entries:
    {
      "moduleNameMapper": {
        "/@assets\/(.*)/": "/Users/ahmedyagoub/plankk/phoenix/src/assets/$1"
      },
      "resolver": undefined
    }
    ```

**Comment by jpkleemans** [comment]
Hi, thanks for reporting. Could you maybe share your project (or a test project) so I can reproduce this error, and investigate how to resolve it.

**Comment by ahyagoub40** [comment]
How would you map it in Jest
I am using the svg loader in vue with typescript project, the way it is described in the readme, when i run my tests, I get that message

**Comment by jpkleemans** [comment]
Hi, have you tried the steps in https://github.com/jpkleemans/vite-svg-loader/issues/35?

**Comment by jpkleemans** [comment]
Closed after 60 days of inactivity
