### ISSUE TITLE
Vite Error: Unrestricted file system access ...

### ISSUE THREAD

**Issue by madebyfabian** [jpkleemans/vite-svg-loader#28]
Hey there, thanks for creating this plugin. Exactly what I needed. 
There is just an error on every dev-server startup that notifies me that this package will break in future vite versions because of file system access. The error message:

```bash
Unrestricted file system access to "/notes/function render(_ctx, _cache) {  return (_openBlock(), _createElementBlock("svg", _hoisted_1, _hoisted_3))}"
For security concerns, accessing files outside of serving allow list will be restricted by default in the future version of Vite. Refer to https://vitejs.dev/config/#server-fs-allow for more details.
```

Now everything works. But I guess this is not something to ignore.

**Comment by madebyfabian** [comment]
Have to add something, it's only when I do
```html
<img src="@/assets/images/logo.svg">
```
directly, without import in JS.

**Comment by jpkleemans** [comment]
Hi, thanks for reporting. I can't reproduce the message. Could you maybe share your project (or a test project), so I can investigate.

**Comment by madebyfabian** [comment]
@jpkleemans  Thanks for your answer. If I use the plugin as the docs tell me to, everything works fine. It's just that direct `<img src="@/assets...` does not work. Will close this :)
