### ISSUE TITLE
Non-prop attributes are not being inherited

### ISSUE THREAD

**Issue by JoseOrtiz** [jpkleemans/vite-svg-loader#29]
When transforming an svg to a component and trying to add an attribute, like `data-testid, and it's not being rendered

Example:
```
<template>
  <div id="app">
    <Icon style="flex: 1" class="icon" data-testid="asfg"/>
  </div>
</template>

<script setup>
import Icon from './icons/icon.svg';
</script>
```

Render as:
```
<div id="app">
  <svg class="icon" viewBox="0 0 360 264" fill="none" xmlns="http://www.w3.org/2000/svg" style="flex: 1 1 0%;">
    ...
  </svg>
</div>
```

**Comment by jpkleemans** [comment]
Hi, I see indeed that those attributes are stripped out.
What are you trying to accomplish with those data attributes? Perhaps it can be done in a different way. For example, you could work with `ref` to access the svg.

**Comment by JoseOrtiz** [comment]
I just wanted to test it's presence, with the `data-testid` approach. I know it could be bypassed, but I want to know if another solution could be possible

**Comment by visionm45** [comment]
i need to use these attributes as well. if they are stripped then this tool is useless to me

**Comment by visionm45** [comment]
I also need the attributes to remain intact. Otherwise i cannot use this

**Comment by Antti** [comment]
I tried fixing it, and it seems that if you return an object with the render function, the attribute inheritance starts working!

Here's a PR: https://github.com/jpkleemans/vite-svg-loader/pull/32
Mind giving it a try?

**Comment by Antti** [comment]
Looks like related: https://github.com/jpkleemans/vite-svg-loader/issues/31
