### ISSUE TITLE
Adding attributes to the <svg> element, besides `class`

### ISSUE THREAD

**Issue by nachtfunke** [jpkleemans/vite-svg-loader#31]
I was wondering, if there is a way that we can somehow get other attributes to appear on the `<svg>` element? I when using inline SVG for icons or purely decorative elements, it'd be important to tell screenreaders to ignore this element via `aria-hidden="true"`.

**Comment by jpkleemans** [comment]
Hi, this is fixed in [v3.1.0](https://github.com/jpkleemans/vite-svg-loader/releases/tag/3.1.0)
