### ISSUE TITLE
Changing the default import option when no query params are given

### ISSUE THREAD

**Issue by floorish** [jpkleemans/vite-svg-loader#41]
Currently an svg without a query param is imported as a Component. Is it possible to change that to the `?url` behavior instead?

Generally, I'm importing svgs as `<img/>` in Vue templates/CSS, and occasionally use the `?component` query param to get a component instead. But all those `<img/>` need a `?url` query param, otherwise they're not loaded when using Vite build.

It's a bit weird to add these `?url` params everywhere, e.g.:
```
.some-class {
    background: url('/src/assets/arrow.svg?url');
}
```

```
<img src="/src/assets/arrow.svg?url">
```

Particularly because the default for other assets is without query params:
```
.some-class {
    background: url('/src/assets/arrow.png');
}
```

```
<img src="/src/assets/arrow.png">
```

And if you accidentally forget the `?url` param you'll only notice missing assets when using `vite build`. When using `vite dev` the assets are still shown correctly, so they're hard to spot when developing.

Changing the default would be a breaking [change](https://github.com/jpkleemans/vite-svg-loader/pull/21#discussion_r681626774), so instead a plugin config option that sets the default would be nice to have.

**Comment by jpkleemans** [comment]
Hi, thanks for the proposal. I agree having a 'default loading behavior' config option would be nice.
Could you create a PR for that?

**Comment by floorish** [comment]
Sure, I'll have a go at it

**Comment by jpkleemans** [comment]
Hi, maybe something like this will work in the `load` method:

```js
async load(id) {
  const [path, query] = id.split('?', 2)

  const importType = defaultImport || query

  if (importType === 'url') {
    return // Use default svg loader
  }

  if (importType === 'raw') {
    return `export default ${JSON.stringify(svg)}`
  }

  if (importType === 'component') {
    // Component compilation code
  }
}
```

**Comment by floorish** [comment]
That's just a different style, right? Perhaps I'm missing something, but that doesn't address the concerns mentioned in the previous post:
- resolveid is non-functional at the moment
- async imports cannot have variables when defaultImport == 'url', this is a limitation of https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars
- how to properly test this?

I'll gladly submit a pr if you don't care about these things.

**Comment by jpkleemans** [comment]
Hi, thanks for your questions. I misinterpreted your first post.

> resolveid is non-functional at the moment

I see, we can remove that function then. Thanks.

> async imports cannot have variables when defaultImport == 'url'

Yes, that is indeed a rollup specific problem. It also doesn't work for other assets:
```
const name = 'logo'
const url = import(`./assets/${name}.png?url`) // Error: Unknown variable dynamic import: ./assets/logo.png?url
```

> how to properly test this?

Hmm, good question. I don't really like copying the whole folder. Can you maybe use [env variables](https://vitejs.dev/guide/env-and-mode.html#env-files) to update the config?

**Comment by floorish** [comment]
No worries, thanks for your replies.

I've added a pr with your suggestion: https://github.com/jpkleemans/vite-svg-loader/pull/42
Had to do a bit of magic in vite.config.js to get testing to work, but should be good now.

**Comment by jpkleemans** [comment]
Added in [v3.2.0](https://github.com/jpkleemans/vite-svg-loader/releases/tag/3.2.0)
