### ISSUE TITLE
color disappear

### ISSUE THREAD

**Issue by Yanyeyeye** [jpkleemans/vite-svg-loader#48]
when i was using the order'?component', my illustration missed partial color.
![test](https://user-images.githubusercontent.com/53677576/163958320-646bf216-9a97-4a88-901e-48ffd468b9cb.png)

**Comment by jpkleemans** [comment]
Hi, have you tried disabling SVGO? See https://github.com/jpkleemans/vite-svg-loader#disable-svgo

**Comment by zumm** [comment]
Also this is may be issue related to Vue3 parser. It doesn't allow use <style> and <script> tags inside component, so if your svg use these tags it may be corrupted.

**Comment by jpkleemans** [comment]
@zumm Yes that' s right. Those kinds of "complex" svg's are tricky to support. In such case, it's better to make a vue component out of it yourself.
