### ISSUE TITLE
[vite] Internal server error: Failed to resolve import "./banner.svg?component"

### ISSUE THREAD

**Issue by jojowwbb** [jpkleemans/vite-svg-loader#49]
"vite": "^2.9.2",
"vite-svg-loader": "^3.2.0",

tsconfig.json
`{
  "compilerOptions": {
    "target": "esnext",
    "useDefineForClassFields": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "strict": true,
    "jsx": "preserve",
    "sourceMap": true,
    "isolatedModules": false,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "typeRoots": [
      "./@types"
    ],
    "lib": [
      "esnext",
      "dom"
    ]
  },
  "include": [
    "@types/*.d.ts",
    "src/**/*.ts",
    "src/**/*.d.ts",
    "src/**/*.tsx",
    "src/**/*.vue"
  ],
  "references": [
    {
      "path": "./tsconfig.node.json"
    }
  ]
}`

then,show the error:

下午11:07:21 [vite] Internal server error: Failed to resolve import "./banner.svg?component" from "src/pages/test/index.vue". Does the file exist?
  Plugin: vite:import-analysis
  File: /Users/glodon/workspace/glodon/mls-web/src/pages/test/index.vue
  4  |  import { ref } from "vue";
  5  |  import { UploadFilled } from "@element-plus/icons-vue";
  6  |  import IconComponent from "./banner.svg?component";
     |                             ^
  7  |  const _sfc_main = /* @__PURE__ */ _defineComponent({
  8  |    emits: ["onChange"],

the file 'banner.svg' had exists！

**Comment by jpkleemans** [comment]
Hi, does it work when omitting the `?component` param?

**Comment by jpkleemans** [comment]
Could you share a [Code Sandbox](https://codesandbox.io/s/) to reproduce the problem?

**Comment by jpkleemans** [comment]
Closed after 60 days of inactivity

**Comment by MageXstarLynn** [comment]
did this error get sorted? I got the same for importing from assets folder & i'm completely new at this,Plz help

![Screenshot_20230126_180611](https://user-images.githubusercontent.com/119503726/214837235-0aa203b6-0bb3-4eaa-b87c-0c715851920f.png)
