### ISSUE TITLE
index.d.ts 不是模块

### ISSUE THREAD

**Issue by qq31311137** [jpkleemans/vite-svg-loader#5]
文件“d:/project/djcars-newpc-web/node_modules/vite-svg-loader/index.d.ts”不是模块。

`"types": ["vite-svg-loader", "vite/client"],`

**Comment by jpkleemans** [comment]
Hi, thanks for your issue.
Could you please share some details where and when you get this error?

**Comment by qq31311137** [comment]
@jpkleemans 
![image](https://user-images.githubusercontent.com/38181726/105671479-c3e22480-5f1d-11eb-8939-308049cf7980.png)

**Comment by jpkleemans** [comment]
Thanks for the screenshot! This is fixed in [v1.4.1](https://github.com/jpkleemans/vite-svg-loader/releases/tag/1.4.1).
