### ISSUE TITLE
Component imports stopped working in version 3.3.0

### ISSUE THREAD

**Issue by cslettengren** [jpkleemans/vite-svg-loader#51]
`import myIcon from '@assets/myIcon.svg?component';`
is importing the icon as a url string since version 3.3.0

**Comment by Oleksii14** [comment]
Also having this issue

**Comment by cslettengren** [comment]
It is only broken when you try running the built javascript files, which makes sense since this is what changed in version 3.3.0:
`
      const isRootRef = viteConfig.command === 'build' && !id.startsWith(viteConfig.root)
      if (!id.match(svgRegex) || isRootRef) {
        return
      }
`

In my case I guess isRootRef will be true and that's why it's returning before even considering what kind of import it should be.

**Comment by chriscalo** [comment]
Just wanted to confirm that I was running into this in my production builds (even though dev worked perfectly) and updating the `vite-svg-loader` version to `3.2.x` fixed it for me.

**Comment by jpkleemans** [comment]
> It is only broken when you try running the built javascript files, which makes sense since this is what changed in version 3.3.0: `const isRootRef = viteConfig.command === 'build' && !id.startsWith(viteConfig.root)` `if (!id.match(svgRegex) || isRootRef) {` `return` `}`
> 
> In my case I guess isRootRef will be true and that's why it's returning before even considering what kind of import it should be.

@cslettengren thanks for your clarification. Now the trick is to figure out why `isRootRef` becomes true. Could you share your alias configuration in `vite.config.js`?

**Comment by jpkleemans** [comment]
I've removed the isRootRef check in [v3.4.0](https://github.com/jpkleemans/vite-svg-loader/releases/tag/3.4.0). So it should be working again!
