### ISSUE TITLE
Vite dev build works perfectly; production build does not load raw SVGs

### ISSUE THREAD

**Issue by adamdehaven** [jpkleemans/vite-svg-loader#54]
I have a Vue 2 + Vite project utilizing this plugin. 

```ts
import svgLoader from 'vite-svg-loader'
...
svgLoader({
  defaultImport: 'raw'
})
```

When I run `vite` (or `yarn dev`) everything works fine and all svg assets are properly rendered.

When I build for production, the assets are instead loaded as a `url` (I think?) and just the asset path is outputted into the DOM
![image](https://user-images.githubusercontent.com/2229946/173711250-3a717833-cfaa-4b88-8d0a-2be0a4e86a9d.png)

I can't seem to put together a decent reproduction, but I'm happy to provide more info or pair as needed.

<details>
<summary>Click to expand more info</summary>

I also control the repository these icons are sourced from. That repository utilizes webpack and Vue 2, and includes a svg rule in the `chainWebpack` config like this:

```js
svgRule.uses.clear()
svgRule
  .oneOf('external')
  .resourceQuery(/external/)
  .use('url')
  .loader('url-loader')
  .options({
    limit: 10000,
    name: 'img/[name].[hash:7].[ext]'
  }).end().end()
  .oneOf('normal')
  .use('raw')
  .loader('raw-loader')
  .end().end()
```

If you look above, this is where the asset URLs (with the hash) are being generated from; however, I can't figure out how to get around this.

</details>

**Comment by adamdehaven** [comment]
It's weird that everything works fine on a dev build, but not production build for certain components

**Comment by jpkleemans** [comment]
That's strange indeed. Have you tried adding `?raw`? That should also work with native JS imports

**Comment by adamdehaven** [comment]
When I add `?raw` to the JS imports/exports, I get an error from the build that it can't find the modules, so that's not an option (they come from a separate package)

**Comment by kingyue737** [comment]
Does this plugin support vue 2?
https://github.com/jpkleemans/vite-svg-loader/issues/10

**Comment by gkatsanos** [comment]
> When I add `?raw` to the JS imports/exports, I get an error from the build that it can't find the modules, so that's not an option (they come from a separate package)

is this still an issue? you can import a file from a separate package if you reference the full name including the node_module namespace e.g. `@organization/my-icons/clock.svg?raw`
