### ISSUE TITLE
How to configure plugins

### ISSUE THREAD

**Issue by soerenmartius** [jpkleemans/vite-svg-loader#55]
Hi!

I am trying to configure some plugins such as `cleanupIDs` and `prefixIds`.
This is my configuration but the loader returns an error 
`[plugin:svg-loader] Plugin name should be specified`

I am using the same SVGs multiple times in the same page but they won't be displayed correctly because of conflicting IDs.

 ```
# vite.config.ts
....
        svgLoader({
            svgoConfig: {
                multipass: true,
                plugins: [
                    {
                        prefixIds: {
                            prefix: ({ path }: { path: string }) => basename(path, '.svg'),
                            delim: '-',
                        },
                    },
                    { removeDoctype: true },
                    { removeComments: true },
                    { cleanupIDs: true },
                    { collapseGroups: true },
                    { removeEmptyContainers: true },
                    { removeUnknownsAndDefaults: { keepDataAttrs: false } },
                ],
            },
        }),

```

Could I get some advice on how to configure plugins? Many thanks!

**Comment by jpkleemans** [comment]
Hi, when looking at the [svgo docs](https://github.com/svg/svgo#configuration), it looks like you should use the following notation when registering plugins:
```js
{
  name: 'prefixIds',
  params: {
    prefix: ({ path }: { path: string }) => basename(path, '.svg'),
    delim: '-'
  }
}
```
Could you try if that works?

**Comment by soerenmartius** [comment]
Thanks - that was helpful. Should have checked the docs myself. My apologies for the noise!

**Comment by jpkleemans** [comment]
You're welcome
