### ISSUE TITLE
SVG is loading is not loading as a component

### ISSUE THREAD

**Issue by abdul-alhasany** [jpkleemans/vite-svg-loader#57]
Hi
The plugin does not seem to load the svg file as a component. 

I imported svg file like this:
```javascript
import ThankYou from '/images/illustrations/placeholders/thankyou.svg?component';
```

I also setup vite.config.ts like so:
```javascript
svgLoader({
   defaultImport: 'component',
})
```

Despite all that I get this error:
```javascript
Uncaught (in promise) DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('/images/illustrations/placeholders/thankyou.svg?component') is not a valid name
```

I am using version 3.4.0, which supposed to solve this issue as stated here: https://github.com/jpkleemans/vite-svg-loader/issues/51

**Comment by kalimah-apps** [comment]
It was an issue because file did not exist on that path. It would be easier if an error message was displayed stating the error.

I created a [pull request](https://github.com/jpkleemans/vite-svg-loader/pull/58) to show the error when the file can not be loaded.
