### ISSUE TITLE
When i use ?component suffix, vite production build cannot find modules

### ISSUE THREAD

**Issue by ZWLau** [jpkleemans/vite-svg-loader#59]
?component suffix works fine in development mode, but when in production mode, the corresponding module cannot be found
 error TS2307: Cannot find module '@/assets/icons/delete.svg?component' or its corresponding type declarations.

**Comment by codfish** [comment]
@ZWLau why'd you close? what was the solution?

**Comment by ZWLau** [comment]
> 

add the global component type definition to compilerOptions.types in tsconfig.json

**Comment by ZWLau** [comment]
> @ZWLau why'd you close? what was the solution?

add the global component type definition to compilerOptions.types in tsconfig.json

**Comment by dmtrbrl** [comment]
@ZWLau can you please provide an example?
It would be also nice to mention this in the docs.

**Comment by riddla** [comment]
See https://github.com/jpkleemans/vite-svg-loader?tab=readme-ov-file#use-with-typescript.
