### ISSUE TITLE
Uncaught DOMException: Failed to execute 'createElement' on 'Document' when loading from public

### ISSUE THREAD

**Issue by jannikbuscha** [jpkleemans/vite-svg-loader#63]
I get this error when im trying to load a svg file as component from public/:
`Uncaught DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('/icons/moon.svg?component') is not a valid name.`

![image](https://user-images.githubusercontent.com/74017697/179285179-13ad2c64-3d0d-41bf-b52d-7ffbf63d8da0.png)

My structure:
![image](https://user-images.githubusercontent.com/74017697/179284985-8cc5c012-d857-441c-84c9-8dc08136a1b3.png)

My `env.d.ts`:
```ts
/// <reference types="vite/client" />
/// <reference types="vite-svg-loader" />
```

My `vite.config.ts`:
```ts
import { fileURLToPath, URL } from 'url'

import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

import svgLoader from 'vite-svg-loader'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue(), svgLoader()],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    }
  }
})
```

Repo:
https://github.com/Backifyco/backify-font-logo-finder

**Comment by luucasrb** [comment]
Having the same error here in production build.

**Comment by htharoldht** [comment]
Also having the same error here in production build.

**Comment by Fulbert** [comment]
I have the same issue. If I use ?raw, the tag name provided is the raw file.

`ncaught (in promise) DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('<?xml version="1.0" encoding="utf-8"?>

[...]`

**Comment by aboutZZ** [comment]
+1. Same error here.

**Comment by jpkleemans** [comment]
Could you try loading the file using a relative path:
```js
import Moon from '../../public/icons/moon.svg'
```

**Comment by htharoldht** [comment]
yes, of course

> Could you try loading the file using a relative path:
> 
> ```js
> import Moon from '../../public/icons/moon.svg?component'
> ```

**Comment by francesco-hayes** [comment]
Any luck on fixing this issue?

**Comment by jpkleemans** [comment]
This behavior is on purpose.

Files you import directly from /public are copied "as-is". This is standard Vite behavior. For example, try loading a .vue file directly from the /public folder: `import Example from '/Example.vue'`, that won't work either.

If the file must necessarily be in the public folder, you can make it work by importing the relative path, for example: `import MyIcon from '../../public/my-icon.svg'`.

**Comment by IARI** [comment]
I have the same Problem.
However my files are not in public, but unter `/src/icons/...`

**Comment by luucasrb** [comment]
In my case, I was using reserved JS/TS words for naming the svg's files, i.e: `import Export from './export.svg?component'`. So, I've changed it to snake case with suffix: `import export_icon from './export.svg?component'`

**Comment by dusan990** [comment]
Once I added this option into the svgr vite.config.ts it started working again without errors `svgr({ include: "**/*.svg", })`

**Comment by tylim88** [comment]
> { include: "**/*.svg", }

your solution work, thanks!

**Comment by phucto-dev** [comment]
> > { include: "**/*.svg", }
> 
> your solution work, thanks!
> 
> another solution that I found is
> 
> ```js
> import logo from '../../assets/logo.svg?react'
> ```
> 
> it works but this will trigger module not found error

Thank you!

**Comment by bztravis** [comment]
For me the fix was to add the include pattern to `vite.config.ts`, it doesn't appear to be required (I assumed the default was `**/*.svg`), so make sure you specify this filter pattern.
