### ISSUE TITLE
Component won't show: `Component is missing template or render function`

### ISSUE THREAD

**Issue by ThaDaVos** [jpkleemans/vite-svg-loader#65]
I am using `https://github.com/antfu/unplugin-vue-components` to automatically load all my components, including the SVG ones - but when I use it - it won't show and my console shows the following warning: `Component is missing template or render function`

**Comment by jpkleemans** [comment]
Hi, did you load `viteSvgLoader()` in your `vite.config.js` file? If yes, then I think unplugin-vue-components doesn't pipe components through the loaded vite plugins. Maybe it's best then to contact them about this.

**Comment by ThaDaVos** [comment]
It does work with other loaders, like the markdown one - and this other one works:
https://github.com/antfu/unplugin-vue-components/issues/9

Also, I am not even loading it through that plugin and it doesn't work:
![image](https://user-images.githubusercontent.com/5251028/187861908-06112581-3845-4d4a-baea-3fbeb10d2465.png)

Logo in question:
![image](https://user-images.githubusercontent.com/5251028/187862048-74f63498-e87e-4031-b64e-66d89dc96689.png)
