### ISSUE TITLE
How to have a dynamic import SVG component

### ISSUE THREAD

**Issue by SirMishaa** [jpkleemans/vite-svg-loader#66]
Hello,

I have an issue when building the Vue (2.7) app: 
> [plugin:vite:dynamic-import-vars] invalid import "/icons/${this.name}.svg?raw". Variable absolute imports are not supported, imports must start with ./ in the static part of the import. For example: import(`./foo/${bar}.js`).

We're using this component everywhere in our application.
SwIcon.vue : 
```vue
<template lang="pug">
  div
    span.block(
      :class="[styleClass, sizeClass]"
      :style="{strokeLinecap: 'round', strokeLinejoin: 'round'}"
      @click="$emit('click')"
      v-html="svgRawContent"
    )
</template>

<script>
export default {
  name: 'SwIcon',
  props: {
    name: {
      type: String,
      default: '',
    },
    unstyled: {
      type: Boolean,
      default: false,
    },
    size: {
      type: String,
      default: 'w-6 h-6',
    },
  },
  data () {
    return {
      svgRawContent: '',
    };
  },
  computed: {
    sizeClass () {
      return this.size;
    },
    styleClass () {
      return this.unstyled ? '' : 'fill-none stroke-current stroke-2';
    },
  },
  // Todo: Replace by Suspense or something else when upgrading to Vue 3 to avoid async lifecycle method
  async mounted () {
    const svgObject = await import(`/icons/${this.name}.svg?raw`);
    this.svgRawContent = svgObject.default;
  },
};
</script>
``` 

Like you can see, we have this import ``await import(`/icons/${this.name}.svg?raw`);`` which is working good in development. 

I guess the problem comes from the fact that during the build phase, since it is dynamic, it is not able to bundle the svg since it does not know them. 

But then, **how can I keep a similar component and make it work?** Even if it has to bundle the whole icon's folder, it's not a big deal if it's lazy loaded.

Thanks in advance, I appreciate it ❤️

PS: I have already check #24, but I don't understand well for my case :/

**Comment by SirMishaa** [comment]
Folder architecture is the following : 
![image](https://user-images.githubusercontent.com/42717232/187897578-dc0f46bc-0000-4dc8-9a70-7129452065e9.png)

Basically, SVG component is here : ``frontend/components/swComponents/SwIcon.vue``
Svg are in this folder: ``frontend/icons``

**Comment by jpkleemans** [comment]
Hi, does it work when you use a relative path: `await import(`../../icons/${this.name}.svg`)`?

**Comment by SirMishaa** [comment]
> Hi, does it work when you use a relative path?
> 
> ```js
> await import(`../../icons/${this.name}.svg`)
> ```

No, I got the following error message : 
> Unknown variable dynamic import: ../../icons/car_discounts/car_lane_departure.svg

It's because the "name", is not a name, but a path (yeah, bad naming, we're doing a lot of refactorings 😅)

**Comment by jpkleemans** [comment]
> Unknown variable dynamic import: ../../icons/car_discounts/car_lane_departure.svg

It seems that the file can't be found. Are you sure `icons/car_discounts/car_lane_departure.svg` exists?

**Comment by SirMishaa** [comment]
![image](https://user-images.githubusercontent.com/42717232/187928422-5526d942-3ee8-4b73-8f6f-ce13769c5a11.png)

Yep : ``frontend/icons/car_discounts/car_lane_departure.svg`` (My IDE generate the path, and I've double-checked) 

I'm not sure the error message mean that, I don't know where does it come from

**Comment by SirMishaa** [comment]
Any idea? :(

**Comment by jpkleemans** [comment]
Can you try to use `defineAsyncComponent`?

```vue
import { defineAsyncComponent } from 'vue'

export default {
  mounted () {
    const svgObject = defineAsyncComponent(() => import(`/icons/${this.name}.svg?raw`))
  }
}
```

**Comment by adrianrivers** [comment]
I'm using this code to render icons from a subfolder dynamically

```vue
<template>
  <IconComponent  :viewBox="viewBox" />
</template>

<script setup lang="ts">
import type { Component } from 'vue'
import { IconName } from '@/types/IconName'

export interface IconProps {
  name: IconName
  fill?: Color
  viewBox?: string | null
}

const props = withDefaults(defineProps<IconProps>(), {
  fill: 'default',
  viewBox: null,
})

const { loader } = createIconMap().get(props.name) ?? {}
const IconComponent = loader ? defineAsyncComponent(loader) : null

function getIconNameFromPath(path: string) {
  const pathSplit = path.split('/')
  const filename = pathSplit[pathSplit.length - 1] || ''
  const iconName = filename.replace('.svg', '')

  return iconName
}

function createIconMap() { 
  const importGlob = import.meta.glob('@/assets/icons/**/*.svg')
  const iconMap = new Map<string, { loader: () => Promise<Component> }>([])

  for (const path in importGlob) {
    const iconName = getIconNameFromPath(path)
    iconMap.set(iconName, { loader: importGlob[path] })
  }

  return iconMap
}
</script>

```
