### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by darthmeme** [jpkleemans/vite-svg-loader#68]
Hey there,

Would you be able to release a new version of vite-svg-loader? There's a fix that was made in https://github.com/jpkleemans/vite-svg-loader/commit/ce3e75ea70a6481fef985dd83f31ac114ceb0a41 that I could really use that wasn't part of `3.5.1`.

**Comment by jpkleemans** [comment]
Hi Akira, thanks for your reminder. I've just pushed release [3.6.0](https://github.com/jpkleemans/vite-svg-loader/releases/tag/3.6.0) which sends the path to svgo.

**Comment by darthmeme** [comment]
Thanks for the quick update! Much appreciated 💪
