### ISSUE TITLE
`?url` results in object with `__file` property instead of an actual url

### ISSUE THREAD

**Issue by ThaDaVos** [jpkleemans/vite-svg-loader#72]
I noticed that if I use `?url` (or not, if it's the default` the resulting thing is not a string but a object with a `__file` property instead - I guess this is a bug?

**Comment by jpkleemans** [comment]
Hi, can you share a [code sandbox](https://codesandbox.io/s/) with the problem? So I can see what's going wrong.

**Comment by ThaDaVos** [comment]
I am happy to tell you that it's already fixed - I added `.svg` to the Vue plugin's include list (the same as is done with `.md` files, at least I saw it done in a tutorial) - but due to that, the `?url` got handled by the vue vite plugin and ended in such strange object - so I am closing this now
