### ISSUE TITLE
The requested module '/node_modules/.vite/deps/vue.js?v=79c678c7' does not provide an export named 'createElementBlock'

### ISSUE THREAD

**Issue by JinZhang-96** [jpkleemans/vite-svg-loader#76]
The requested module '/node_modules/.vite/deps/vue.js?v=79c678c7' does not provide an export named 'createElementBlock'

**Comment by jpkleemans** [comment]
Hi, could you please reproduce the problem, for example in a [Code Sandbox](https://codesandbox.io/s/)?

**Comment by dephiros** [comment]
Run in this error as well. Let me try to recreate a code sandbox

**Comment by kingyue737** [comment]
It seems to be the version of `@vue/compiler-sfc`. To support vue 2.7, may need to move `@vue/compiler-sfc` from dependencies to peer dependencies.
```json
// package.json
{
  "peerDependencies": {
    "@vue/compiler-sfc": "^2.7.0 || ^3.0.0",
    "vite": "^2.0.0 || ^3.0.0-0 || ^4.0.0"
  },
  "peerDependenciesMeta": {
    "@vue/compiler-sfc": {
      "optional": true
    }
  },
}
```

I've made a fork for Vue 2 for temporary workaround: https://github.com/kingyue737/vite-plugin-vue2-svg

**Comment by romansp** [comment]
Another band-aid solution is to force version of `@vue/compiler-sfc` via package.json `resolutions` if you're using `Yarn`.

```
// package.json
"dependencies": {
  "vue": "^2.7.14"
},
"resolutions": {
  "@vue/compiler-sfc": "^2.7.14"
}
```

And for typescript to make Volar and `vue-tsc` happy need to also adjust some types. That's because `vue@2` doesn't export separate `FunctionalComponent` type.
```ts
declare module "*.svg?component" {
  import { Component } from "vue";

  const src: Component;
  export default src;
}

declare module "*.svg?url" {
  const src: string;
  export default src;
}

declare module "*.svg?raw" {
  const src: string;
  export default src;
}

declare module "*.svg?skipsvgo" {
  import { Component } from "vue";

  const src: Component;
  export default src;
}
```

**Comment by jaw52** [comment]
I made a plugin that supports both vue3.x and vue2.7 [unplugin-svg-vue-component](https://www.npmjs.com/package/unplugin-svg-vue-component)

**Comment by gkatsanos** [comment]
Not sure if this is something we can fix...
