### ISSUE TITLE
Customize the destination folder in dist

### ISSUE THREAD

**Issue by antoniogiroz** [jpkleemans/vite-svg-loader#79]
Hi!

It would be great if we could define the destination folder for the generated componentes. Currently they are generated in the root of the dist folder.

Example:

```ts
svgLoader({
  dest: './dist/icons'
})
```

Thanks!

**Comment by gkatsanos** [comment]
@antoniogiroz I think you're looking for vite-specific configuration and not something that's related to this specific plugin. Maybe https://vitejs.dev/config/build-options.html#build-outdir ?
