### ISSUE TITLE
svg property changes

### ISSUE THREAD

**Issue by MentalGear** [jpkleemans/vite-svg-loader#8]
Is it possible with this lib to change svg properties like fill color, border color, etc?

**Comment by jpkleemans** [comment]
Yes, you can use css to color the svg:

```vue
<template>
  <MyIcon class="icon" />
</template>

<style>
.icon path {
  fill: blue;
}
</script>
```

**Comment by MentalGear** [comment]
thanks man for the quick reply. One last thing: Does the plugin embed svgs into the main html file, or are they loaded on demand and cache-able ?

**Comment by jpkleemans** [comment]
Yes, you can lazy load them using `defineAsyncComponent`. See https://v3.vuejs.org/guide/component-dynamic-async.html#async-components

**Comment by MentalGear** [comment]
Awesome
