### ISSUE TITLE
Class name conflict with custom class name "icon"

### ISSUE THREAD

**Issue by ttqftech** [jpkleemans/vite-svg-loader#86]
If the <style> area in a .vue file contains a custom class name "icon", the loader conflicts.
Any loaded svg will have the custom "icon" style.

using:
vite-svg-loader: Both 4.0.0 and 3.6.0 has this problem.
vite: 4.0.0
less: 4.1.3 (using <style lang="less" scoped>)
vue: 3.2.45

**Comment by gkatsanos** [comment]
Hey, @ttqftech could you post a minimal reproduction link on https://stackblitz.com/ ?
