### ISSUE TITLE
Usage with SVGO (Imagemin)

### ISSUE THREAD

**Issue by chojnicki** [jpkleemans/vite-svg-loader#9]
Hi. Any docs how to use this plugin together with SVGO?
Plugin alone on fresh Vue 3 + Vite works well. Unfortunately after adding [vite-plugin-imagemin](https://github.com/anncwb/vite-plugin-imagemin) with SVGO build-in I have two issues (after build):
1. SVG via import is not compressed at all.
2. SVG as normal asset `<img src="" />` looks like this:
`<img src="function c(n,s){return e(),t(&quot;svg&quot;,r,[l])}" alt="">`
Thing is - after removing "vite-svg-loader" everything works, I can get my optimized .svg file. This plugin should work only with .svg files imported as component, but somehow it messes with my .svg assets and imagemin. Why?

vite.config.ts
```
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import viteSvgLoader from 'vite-svg-loader'
import viteImagemin from 'vite-plugin-imagemin'
// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    viteImagemin(),
    viteSvgLoader(),
  ]
})
```

Component
```
<template>
  <img src="/src/assets/images/header/news.svg" alt="Test as asset">
  <NewsIcon />
</template>

<script lang="ts">
  import { defineComponent } from 'vue'
  import NewsIcon from '/src/assets/images/header/news.svg'

  export default defineComponent({
    name: 'App',
    components: {
      NewsIcon
    }
  })
</script>
```

Result
```
<img src="function m(a,n){return e(),t(&quot;svg&quot;,i,[c])}" alt="Test as asset">
<svg xmlns="http://www.w3.org/2000/svg" width="21" height="20" viewBox="0 0 21 20">UNCOMPRESSED SVG SOURCE</svg>
```

**Comment by jpkleemans** [comment]
Hi, thanks for your question.

The plugin does not handle SVG compression and indeed I see that it does not work well with vite-plugin-imagemin either.

I'm thinking about adding support for SVGO in the future, but can't give an ETA. Feel free to open a Pull Request if you have the time to contribute that functionality to the plugin.

P.S. I always compress my SVG images beforehand with a tool like https://jakearchibald.github.io/svgomg/.

**Comment by rightaway** [comment]
Is there any Vite plugin you know of that integrates svg with svgo? Compressing beforehand isn't a good option when there's lots of svgs being added and removed regularly. That would defeat the benefit of using a build tool which should do it on the fly just like with js or css.

**Comment by jpkleemans** [comment]
@rightaway @chojnicki SVGO is now integrated in version [2.0.0](https://github.com/jpkleemans/vite-svg-loader/releases/tag/2.0.0)
