### ISSUE TITLE
Issue importing SVG from a different package

### ISSUE THREAD

**Issue by maurocasas** [jpkleemans/vite-svg-loader#90]
Hello there!

I have a simple test to validate how the SVG loader works, and I'm running this line:

`import HomeMinor from '@shopify/polaris-icons/dist/svg/HomeMinor.svg';`

And when Vite builds I get `[vite] Internal server error: Missing "./dist/svg/HomeMinor.svg" export in "@shopify/polaris-icons" package`

I don't fully understand what's happening, as the file path is indeed correct, but it's prepending `./` to the path

🤔 

Am I doing anything wrong here and I'm not seeing it?

Appreciate the time and effort 🙏 
Best
M

**Comment by jpkleemans** [comment]
Hi, thanks for your question.
I think this is because `@shopify/polaris-icons/dist` has an `index.js` file that has an `exports`, which "overwrites" the normal exports of that folder. This is a known issue in Vite, see https://github.com/vitejs/vite/issues/1505

**Comment by maurocasas** [comment]
Thank you @jpkleemans ! I've decided to copy-paste the icons in a folder for the time being
