### ISSUE TITLE
deprecated sourcemap-codec@1.4.8

### ISSUE THREAD

**Issue by mahnunchik** [jpkleemans/vite-svg-loader#93]
```
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
```

```
└─┬ vite-svg-loader@4.0.0
  └─┬ @vue/compiler-sfc@3.2.47
    └─┬ magic-string@0.25.9
      └── sourcemap-codec@1.4.8
```

According to the documentation of `@vue/compiler-sfc` module https://www.npmjs.com/package/@vue/compiler-sfc it may be replaced by main `vue` package.

**Comment by gkatsanos** [comment]
@mahnunchik sourcemap-codec isn't a direct dependency of this package. I don't see what we can do about it?

**Comment by mahnunchik** [comment]
@gkatsanos According to the documentation of @vue/compiler-sfc it should be replaced by main vue package as:

```js
const { compileTemplate } = require('vue/compiler-sfc')
// or

import { compileTemplate } from 'vue/compiler-sfc/index.js';
```

**Note: as of 3.2.13+, this package is included as a dependency of the main `vue` package and can be accessed as `vue/compiler-sfc`. This means you no longer need to explicitly install this package and ensure its version match that of `vue`'s. Just use the main `vue/compiler-sfc` deep import instead.**

**Comment by gkatsanos** [comment]
@mahnunchik : https://github.com/jpkleemans/vite-svg-loader/pull/103/files not sure this is the case, by looking a bit around https://stackoverflow.com/questions/63863222/after-upgrading-to-vue-3-cannot-find-module-vue-compiler-sfc-package-json it seems that when you go to Vue3 , you need to explicitely add the vue compiler sfc as a separate dependency (exactly as we had).
Feel free to jump in the PR if you see something obviously wrong :)

**Comment by mahnunchik** [comment]
@gkatsanos great, thank you! I think `vue` can be added to `peerDependencies`.

**Comment by mahnunchik** [comment]
@gkatsanos could you please release 4.1 to npm

**Comment by gkatsanos** [comment]
I dont have publish permissions. @jpkleemans

**Comment by jpkleemans** [comment]
Released
