### ISSUE TITLE
Nuxt component auto-import

### ISSUE THREAD

**Issue by mrleblanc101** [jpkleemans/vite-svg-loader#95]
Hi,
Is it possible to make this work with Nuxt component auto-import ?
If I use `<SvgName>`, it would generate `import SvgName from '@/assets/svg/SvgName.svg?component';`
It would be nice to be able to prefix the SVG too, like `<ISvgName>`. We use the capital `i` prefix for all "icons"

**Comment by ExEr7um** [comment]
Check out https://github.com/cpsoinos/nuxt-svgo.

**Comment by gkatsanos** [comment]
We should keep this rather generic, you can use a more nuxt-specific module otherwise liek the one linked above.
